spring.application.name=NexoBank2

##DataBase
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/nexobank2}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.username=${DB_USERNAME:postgres}

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

##OpenApi Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

##MailSender
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

##Security
jwt.secret.key=${JWT_SECRET_KEY}
jwt.token.time=${JWT_TOKEN_TIME:3600000}

##Logging
logging.level.com.example.nexobank2.security=DEBUG
logging.level.org.springframework.security=DEBUG
