spring.application.name=NexoBank2
spring.datasource.url=jdbc:postgresql://localhost:5433/nexobank2
spring.datasource.password=postgres
spring.datasource.username=postgres

##OpenApi Scalar
scalar.enabled=true
scalar.path=/scalar
scalar.url=http://localhost:8080/v3/api-docs

##MailSender
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aab97970@gmail.com
spring.mail.password=ewdqgmdefftjticu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
